### ISSUE TITLE
Lots of NaNs and/or infinity values in last and 2nd-to-last windows during windowed extraction

### ISSUE THREAD

**Issue by codaich** [DDMAL/jSymbolic2#25]
This is a separate issue from the problematic feature values in Issue #20, since this problem is not limited in vertical features, and is specific to the final windows of windowed extraction.

**Comment by dinamix** [comment]
I remember this happening to me once in a while. This could be due to the fact that the last windows have no data.

**Comment by codaich** [comment]
If this is the case, then we should exclude final windows that do not hold any data from bing saved. 

Related questions: Why would there be a final window with no data? Notes that are being held that had onsets in previous windows should still be considered. This should only happen in cases where final windows contain nothing but rests, which should be relatively rare?

**Comment by dinamix** [comment]
I have gone through about 10 files at random in the test sets and split them up and looked and listened to the MIDI and it seems to me that the this occurs in the last windows that are generally very short. So if the window size is 10 seconds, the last window may be < 3 seconds (for example). The pieces will end in the 2nd to last window and so the last window will only have silence. I also found that some piece have NaNs at the beginning. This is due to the fact that some piece start with only percussion. Both of these seems to occur less often than not. I will continue to go through some more files.

**Comment by codaich** [comment]
If the last window of a piece contain nothing, then let's exclude it (i.e. not save features for it). Let's not exclude windows that contain nothing if they occur anywhere else, however (I'll have to think about what to do with them). If there is nothing in a window except for Channel 10 stuff, the we should always save its features (even if it's the last window), since some of the features are based on or include Channel 10 content.

**Comment by dinamix** [comment]
Partially fixed (maybe fully) by last commit in UtilityClasses : commit bdaff47c913f8e5cddc8cb0a3a9bcf5bde6b666c

**Comment by codaich** [comment]
Good, no longer seeing NaNs and/or infinity values in windows. Issue closed.
