### ISSUE TITLE
OutOfMemoryError still occuring on some large files

### ISSUE THREAD

**Issue by dinamix** [DDMAL/jSymbolic2#3]
Look into why an OutOfMemoryError is being caused in files such as Mendelssohn's Midsummer Night Dream and also why there is an inconsistency in error message between the GUI and the command line.

**Comment by codaich** [comment]
Details: Still running out of memory when I try to extract features from the Mendelssohn's Midsummer Night Dream in the 250 SLAC MIDI files. The 950 Bodhidharma MIDI files have not yet been checked in this respect, but also need to be.

The GUI reports the error with Midsummer Night Dream, but the command line interface does not. For Midsummer Night Dream, the command line interface simply does not write any features to the output feature values ACE XML file, and no error message of any kind is generated. The GUI ends feature extraction after reporting the error, without extracting features from the remaining files.

To solve the memory issue, the amount of memory assigned can simply be increased if space efficiency is too messy to improve further at this point. 

Regardless of the solution, testing still needs to be done to ensure that when memory is run out of, the command line interface reports it in a highly noticeable way (but continues processing other files). It would also be nice if the GUI also continued processing other files rather than ending execution (and continues to report the error, of course).

We also need to make sure that memory problems don't cause problems with the Rodan workflow.

**Comment by codaich** [comment]
Good. After the new fixes, features were succesfully extracted from all Bodhidharma MIDI, SLAC MIDI, and test MEI files, with no memory errors. There are still some problems in the code in how memory is treated, but these are not yet significantly impacting processing, and they can be addressed as a separate issue (#21).
