### ISSUE TITLE
errors when saving the analysis outputs

### ISSUE THREAD

**Issue by adrienchaton** [DDMAL/jSymbolic2#54]
Hello,

I am trying to use the jMIR_3_1_developer/jSymbolic2/dist/jSymbolic2.jar to analyze midi data.
The processing in the GUI seems working until
>>> Feature extraction complete.

Then the saving doesn't work and throw errors:
>>> Features succesfully extracted and saved from 0 of 2 attempted files.
>>> The saved ACE XML Feature Values file is empty as a result.

Which corresponds to the error reports:
WARNING: Saving of Weka ARFF and/or CSV files was aborted. The ./extracted_feature_values.xml file is not formatted properly.
Details of the problem: For input string: "1,976E3"

As a result, there is no .csv file, only the two .xml which apparently cannot be formatted properly ..

I am running this on Mac OS 10.14 ; please could you help with sorting these errors ?

Thanks

**Comment by codaich** [comment]
Hi Adrien

Thanks for your interest in jSymbolic,. 

One possible explanation may be that the libraries that generate the CSV and Weka ARFF file formats require that period decimal delimiters be used rather than comma decimal delimiters in your operating system’s regional settings. 

We’re aware that this is an important problem, and we will be correcting it in the upcoming SourceForge release version of jSymbolic (and the fix should be incorporated sometime before that into the in-development version hosted on GitHub). This fix which will override the system’s regional settings. Unfortunately, in the current version of jSymbolic it is unfortunately necessary to change your operating system’s regional settings to use period rather than comma delimiters. If this is problematic, the good news at least is that jSymbolic's own native ACE XML feature file format works equally well with either decimal delimiter, so if you do  not wish to change your regional settings, you can use ACE XML as the output format rather than CSV or ARFF.

Apologies for this inconvenience.

If this doesn’t solve your problem, would you be willing to share the two MIDI files and I could take a closer look?

Thanks for bring your problem to our attention,
Cory

**Comment by adrienchaton** [comment]
Hi Cory,

That was the right pointer, I switched from French to UK and now it works 👍 
Thank you for the fast fix !

Adrien
