### ISSUE TITLE
MEI files validation

### ISSUE THREAD

**Issue by ikyriazi** [DDMAL/jSymbolic2#55]
I am using jSymbolic GUI (just installed it) and I get validation errors by all MEI files I am trying to import, also the ones coming from the MEI GitHub repository itself. Is this maybe a bug or are there special configurations to be considered?

**Comment by codaich** [comment]
The MEI parser we implemented was last updated in 2017, and the MEI standard has changed since then. So, unless your MEI files are compliant with the basic MEI standard as it existed prior to that (which, reasonably enough, they probably aren't), jSymbolic will unfortunately probably not be able to parse them. An update to the MEI parser we use is unfortunately not included in the near-term jSymbolic 3 update schedule. I therefore suggest that you convert your MEI files to MIDI as a pre-processing step, which jSymbolic will then be able to parse without problem (some data is lost by converting to MIDI, of course, but the jSymbolic features are designed to take MIDI's shortcomings into account). Sorry for the inconvenience.

**Comment by ikyriazi** [comment]
Thanks for the clarification! jSymbolic worked indeed with legacy MEI 2.1 files, but not with MEI 3.0 (although this version is still pre-2017). Converting to midi did work.
