### ISSUE TITLE
Problem with windowed feature extraction

### ISSUE THREAD

**Issue by codaich** [DDMAL/jSymbolic2#9]
Extracting windowed features using either the command line or the GUI (and using all 1-dimensional features, but no multi-D features) from the Mozart_Quintett_2013.mei file you sent me earlier results in a "Error found in file : C:\Git\jSymbolic2\dist\Mozart_Quintett_2013.mei. Error Message : 1." mesage. I also noticed this problem in quite a few other files.

**Comment by codaich** [comment]
Once this is fixed, try saving ARFF and CSV windowed features as well. Based on some initial investigtaions, just including xerces.jar in the jSymbolic2 libraries may fix the problem that you alerted me to last year.

**Comment by dinamix** [comment]
This works if ARFF and CSV are not specified. If they are, then the problem is the one we encountered since last summer. I have xerces.jar as a library in my build and it still does not work when the file is windowed and ARFF and CSV conversions are specified. From what I remember, it was a problem in ACE/weka.

**Comment by codaich** [comment]
OK, I've confirmed that you're correct. I'll take over this issue and look at the relevant ACE codeACE.
